# Generated by Django 5.1.7 on 2025-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_options_course_category_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('text', 'Text Lesson'), ('mixed', 'Mixed Content')], default='text', max_length=20),
        ),
    ]
