# Generated by Django 5.1.7 on 2025-05-03 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_question_max_points_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='playlist_id',
        ),
    ]
