# Generated by Django 5.1.7 on 2025-07-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lesson_content_type_remove_lesson_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessoncontent',
            old_name='description',
            new_name='text_content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
