# Generated by Django 5.1.7 on 2025-07-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_description_lessoncontent_text_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
