# Generated by Django 5.1.7 on 2025-07-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_lessoncontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration in minutes'),
        ),
    ]
