# Generated by Django 5.1.7 on 2025-08-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lessoncontent_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('resource_type', models.CharField(choices=[('link', 'Webpage Link'), ('document', 'Document')], default='link', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order of resource in the lesson')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('lesson', 'position')},
            },
        ),
    ]
